document.addEventListener("DOMContentLoaded", function entrega(){
    const sem_demandas = document.getElementById("sem_demandas")
    const demanda = document.getElementById("pedido")
    const aceitar = document.getElementById("aceitar")
    const ocultar = document.getElementById("ocultar")
    const sem_entregas = document.getElementById("sem_entrega_ativa")
    const entrega_ativa = document.getElementById("entregasativas")
    aceitar.addEventListener("click", function pedidoaceito(){
        sem_demandas.classList.remove("displaynone")
        sem_demandas.classList.add("displayblock")
        demanda.classList.remove("displayblock")
        demanda.classList.add("displaynone")
        sem_entregas.classList.remove("displayblock")
        sem_entregas.classList.add("displaynone")
        entrega_ativa.classList.remove("displaynone")
        entrega_ativa.classList.add("displayblock")
    })
    ocultar.addEventListener("click", function pedidooculto(){
        sem_demandas.classList.remove("displaynone")
        sem_demandas.classList.add("displayblock")
        demanda.classList.remove("displayblock")
        demanda.classList.add("displaynone")
    })
})